name: Prepare README for GitHub Mirror

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'profile/**'

jobs:
  transform:
    runs-on: codeberg-small
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Transform and Prepare Structure
        run: |
          mkdir -p profile
          sed 's|(\(img/\)|(../\1|g' README.md > profile/README.md

      - name: Commit changes back to Codeberg
        run: |
          git config user.name "ProFed CI Bot"
          git config user.email "bot@joinprofed.social"
          
          git add profile/README.md
          
          if git diff-index --quiet HEAD --; then
            echo "Keine Änderungen am README festgestellt."
          else
            git commit -m "ci: update transformed README for GitHub mirror [skip ci]"
            git push https://x-access-token:${{ secrets.CODEBERG_WRITE_TOKEN }}@codeberg.org/${{ github.repository }}.git HEAD:main
          fi

